"""remove_restaurant_id_from_user

Revision ID: 0f3ee4a5926f
Revises: 90eedaf05f0f
Create Date: 2025-10-09 06:46:34.002416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3ee4a5926f'
down_revision: Union[str, Sequence[str], None] = '90eedaf05f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_restaurant_id'), table_name='user')
    op.drop_constraint(op.f('user_restaurant_id_fkey'), 'user', type_='foreignkey')
    op.drop_column('user', 'restaurant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('restaurant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_restaurant_id_fkey'), 'user', 'restaurant', ['restaurant_id'], ['id'])
    op.create_index(op.f('ix_user_restaurant_id'), 'user', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###
