"""add logo_url to restaurant

Revision ID: 6cda9d1e7a0b
Revises: a3cfe5d01e59
Create Date: 2026-01-27 06:22:19.298259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cda9d1e7a0b'
down_revision: Union[str, Sequence[str], None] = 'a3cfe5d01e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'logo_url')
    # ### end Alembic commands ###
