"""add email_verified to user

Revision ID: a3cfe5d01e59
Revises: 6f7f6a284a77
Create Date: 2026-01-27 05:22:53.463292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3cfe5d01e59'
down_revision: Union[str, Sequence[str], None] = '6f7f6a284a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add email_verified column with a default value of False
    # Using server_default so existing rows get the default value
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))
    
    # Optionally remove the server_default after the column is added (keeps model as source of truth)
    # op.alter_column('user', 'email_verified', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
