"""Add unique constraint to membership

Revision ID: e0e23050ccaa
Revises: 6cda9d1e7a0b
Create Date: 2026-01-28 07:12:52.991857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e23050ccaa'
down_revision: Union[str, Sequence[str], None] = '6cda9d1e7a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_restaurant', 'membership', ['user_id', 'restaurant_id'])
    op.alter_column('user', 'email_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint('uix_user_restaurant', 'membership', type_='unique')
    # ### end Alembic commands ###
